### ISSUE TITLE
tests consistently failing against grin_chain

### ISSUE THREAD

**Issue by antiochp** [ignopeverell/grin#89]
The following tests appear to be failing consistently on `master` when run using 
`cargo test -p grin_chain` - 

* mine_empty_chain
* mine_forks 

```
    Finished dev [unoptimized + debuginfo] target(s) in 86.2 secs
     Running target/debug/deps/grin_chain-7bcc00f37abf022a

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/mine_simple_chain-028713fafb6b7973

running 2 tests
test mine_forks ... FAILED
test mine_empty_chain ... FAILED

failures:

---- mine_forks stdout ----
	thread 'mine_forks' panicked at 'assertion failed: `(left == right)` (left: `3`, right: `1`)', chain/tests/mine_simple_chain.rs:110
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- mine_empty_chain stdout ----
	thread 'mine_empty_chain' panicked at 'assertion failed: `(left == right)` (left: `18`, right: `1`)', chain/tests/mine_simple_chain.rs:83


failures:
    mine_empty_chain
    mine_forks

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test mine_simple_chain'
```

**Comment by yeastplume** [comment]
I think those tests assume that you're starting from an empty chain, (which automated testing does and therefore works in continuous integration). Delete the .grin and .grin2 directories and try again. It's no harm to change them to have them remove their test directories first like the tests in grin/simulnet do, though.

**Comment by antiochp** [comment]
Awesome thanks for the info - that was driving me crazy for a minute.
I can work on updating the chain tests to clean up those dirs.
